### ISSUE TITLE
Emoji Tool Errors

### ISSUE THREAD

**Issue by J-Cook-jr** [kianenigma/kanaria-hatchery#1]
<img width="1251" alt="Screen Shot 2021-05-18 at 3 45 49 PM" src="https://user-images.githubusercontent.com/62865359/118716428-cdf0a180-b7f2-11eb-9947-308355493792.png">
Hi, I followed the instructions in your READ.ME for the emoji tool but I keep getting this error after trying to run it. Can you help me out? Thanks!

**Comment by kianenigma** [comment]
The file that you pass to `--seed` must contain the **raw seed** or the mnemonic seed, not a json file.
